cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - 8.10.0
install:
  - cd ./frontend
  - yarn install
  - yarn add coveralls
script: cd ./frontend && yarn run cover --maxWorkers=4 --ci
after_script: cat ./frontend/coverage/lcov.info | ./frontend/node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
notifications:
  email: false