cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - 8.10.0
install:
  - cd ./frontend
  - yarn install
  - yarn add coveralls
script: yarn run cover --maxWorkers=4 --ci
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
  - PWA-708-unit-test-integration
notifications:
  email: false