export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAILED = 'UPDATE_USER_ADDRESS_FAILED';
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS_FAILED = 'DELETE_USER_ADDRESS_FAILED';
export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const DELETE_ADDRESSES = 'DELETE_ADDRESSES';
