export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_MAIL_FAILED = 'UPDATE_USER_MAIL_FAILED';

export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES';
export const USER_ADDRESSES_RECEIVED = 'USER_ADDRESSES_RECEIVED';
export const USER_ADDRESSES_FAILED = 'USER_ADDRESSES_FAILED';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS';
export const ADD_USER_ADDRESS_FAILED = 'ADD_USER_ADDRESS_FAILED';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAILED = 'UPDATE_USER_ADDRESS_FAILED';
export const DELETE_USER_ADDRESSES = 'DELETE_USER_ADDRESSES';
export const DELETE_USER_ADDRESSES_CONFIRMED = 'DELETE_USER_ADDRESSES_CONFIRMED';
export const DELETE_USER_ADDRESSES_SUCCESS = 'DELETE_USER_ADDRESSES_SUCCESS';
export const DELETE_USER_ADDRESSES_FAILED = 'DELETE_USER_ADDRESSES_FAILED';
export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const USER_ADDRESS_VALIDATION_FAILED = 'USER_ADDRESS_VALIDATION_FAILED';
export const USER_ADDRESS_FORM_LEAVE = 'USER_ADDRESS_FORM_LEAVE';

export const USER_CONFIG_RECEIVED = 'USER_CONFIG_RECEIVED';
export const USER_CONFIG_FAILED = 'USER_CONFIG_FAILED';

export const USER_VIEW_IS_LOADING = 'USER_VIEW_IS_LOADING';
