export const APP_BAR_SAVE_BUTTON_CLICK = 'NAVIGATOR_SAVE_BUTTON_CLICK';
export const APP_BAR_SAVE_BUTTON_DISABLE = 'NAVIGATOR_SAVE_BUTTON_DISABLE';
export const APP_BAR_SAVE_BUTTON_ENABLE = 'NAVIGATOR_SAVE_BUTTON_ENABLE';
