export const NAVIGATOR_USER_ADDRESS_BUTTON_CLICK = 'NAVIGATOR_SAVE_BUTTON_CLICK';
export const NAVIGATOR_USER_ADDRESS_BUTTON_SHOW = 'NAVIGATOR_USER_ADDRESS_BUTTON_SHOW';
export const NAVIGATOR_USER_ADDRESS_BUTTON_HIDE = 'NAVIGATOR_USER_ADDRESS_BUTTON_HIDE';
export const NAVIGATOR_USER_ADDRESS_BUTTON_DISABLE = 'NAVIGATOR_USER_ADDRESS_BUTTON_DISABLE';
export const NAVIGATOR_USER_ADDRESS_BUTTON_ENABLE = 'NAVIGATOR_USER_ADDRESS_BUTTON_ENABLE';
